### ISSUE TITLE
v2 feature proposal

### ISSUE THREAD

**Issue by scDisorder** [rovergulf-archive/ngx-slice-kit#131]
- [ ] ❓which cards do we need?? // #130
- [ ] media module // #135 then #132 #133 #134 
- [ ] badge & chips use cases // #127 and #129 
- [ ] overlay module – to handle all modal components and prevent inner interaction #48 
- [ ] popover component, `<ng-content>` based #128 
- [ ] use font icons, and i think it is better to use good one ready community collection instead our own, bad handled (as i think) SVGs, as I mentioned in #105 
- [ ] add website internationalization support #126 
- [x] Test coverage badge resolved in #164 
- [ ] markdown reader
- [ ] Add ![npm](https://img.shields.io/npm/dw/ngx-slice-kit) to README.md and website main page
- wysiwyg ??
- theme gradient color support
- ... am i missing something?
