### ISSUE TITLE
Documentation examples v1

### ISSUE THREAD

**Issue by scDisorder** [rovergulf-archive/ngx-slice-kit#32]
- [x] Buttons module
  - [x] Button component - partially #171
  - [x] Button group component - #172
  - [x] Icon component- #172
- [x] Dropdowns module - #185
  - [x] Autocomplete component
  - [x] Context menu component
  - [x] Select component
- [x] Inputs module
  - [x] Checkbox component- #172
  - [x] Input component - #183 
  - [x] Radio component – partially #147 
  - [x] Textarea component- #172
  - [x] Toggle component - partially #143 , #147  
- [x] Layout module
  - [x] Carousel component - #194
  - [x] Divider component - #172
  - [x] Pagination component- #177
  - [x] Progress component-#179
  - [x] Slider component-#179
- [x] Modals module
  - [x] Alert service - #180 
  - [x] Dialog service - #172
  - [x] Popup service - #172, #192
  - [x] Tooltip directive - #172
- [x] Navigation module
  - [x] Nav-menu component
    - [ ] stackblitz demo
  - [x] Nav-tabs component
  - [x] Sidenav component - #178
    - [ ] [stackblitz demo](https://stackblitz.com/edit/ngx-slice-kit-sidenav-example)
  - [x] Tabs component
